pipeline {
    agent any
    tools { 
        maven "$MyMaven"
	jdk "$MyJava"
    }
    stages {
        stage('Build-new') {
            steps {
		sh '''
		    echo "PATH = ${PATH}"
		    echo "M2_HOME = ${M2_HOME}"
		'''
                 sh 'mvn -v' 
                 sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
